// Canvas Variables
var canvas;
var canvasContext;
var canvasBGColor;
// FPS
var framesPerSecond;
// Images
//var imageName = document.createElement("img");		
// Score
var playerScore;
// Keyboard Handling
var holdLeft = false;
var holdRight = false;
var holdUp = false;
var holdDown = false;
var holdL = false;
var holdW = false;
var holdS = false;
var holdA = false;
var holdD = false;
var holdQ = false;
var holdE = false;
var holdZ = false;
var holdX = false;
var hold0 = false;
var hold1 = false;
var hold2 = false;
var hold3 = false;
var hold4 = false;
var hold5 = false;
var hold6 = false;
var hold7 = false;
var hold8 = false;
var hold9 = false;
var holdU = false;
var holdJ = false;
var holdH = false;
var holdK = false;
var holdY = false;
var holdI = false;
var holdN = false;
var holdM = false;
var unHold = false;
// Keyboard constants
const KEY_LEFT_ARROW = 37;
const KEY_UP_ARROW = 38;
const KEY_RIGHT_ARROW = 39;
const KEY_DOWN_ARROW = 40;
const KEY_SPACE = 32;
const KEY_L = 76;
const KEY_W = 87;
const KEY_S = 83;
const KEY_A = 65;
const KEY_D = 68;
const KEY_Q = 81;
const KEY_E = 69;
const KEY_Z = 90;
const KEY_X = 88;
const KEY_0 = 48;
const KEY_1 = 49;
const KEY_2 = 50;
const KEY_3 = 51;
const KEY_4 = 52;
const KEY_5 = 53;
const KEY_6 = 54;
const KEY_7 = 55;
const KEY_8 = 56;
const KEY_9 = 57;
const KEY_U = 85;
const KEY_J = 74;
const KEY_H = 72;
const KEY_K = 75;
const KEY_Y = 89;
const KEY_I = 73;
const KEY_N = 78;
const KEY_M = 77;
